In [1]:
# Import Required Libraries

import pandas as pd
import numpy as np

In [2]:
# Load Dataset Using Pandas

df = pd.read_csv("/content/Retail_Dataset_Cleaned_1509.csv")

print("Dataset Loaded Successfully")

Dataset Loaded Successfully

In [3]:
# Display First Five Records

df.head()

,Store_ID,Store_Name,Brand_Name,Store_Type,City,City_Tier,Product_Name,Category,Sub_Category,Product_Stage,...,Brand_Loyalty,Brand_Awareness,Price_Competitiveness,Weather_Impact,Delivery_Time,Shipping_Cost,Month,Year,Quarter,Season
0,Bx_Pune_034,Brandx_India Superstore Pune,Brandx_India,Flagship,Pune,Tier1,Green Tea 100G,Groceries,Tea,Declining,...,70.8,75.7,Standard,Low,6.0,57.0,1,2022,Q1,Spring
1,Bx_Mumbai_023,Brandx_India Superstore Mumbai,Brandx_India,Street Store,Mumbai,Metro,White Sugar 1Kg,Groceries,Sugar,Declining,...,80.5,81.5,Competitive,Low,4.0,99.0,1,2022,Q1,Spring
2,Bx_Pune_073,Brandx_India Trends Pune,Brandx_India,Flagship,Pune,Tier1,Levi'S T-Shirt,Clothes,T-Shirts,Declining,...,68.5,76.7,Standard,Medium,4.0,101.0,1,2022,Q1,Spring
3,Bx_Chennai_061,Brandx_India Trends Chennai,Brandx_India,Mall Store,Chennai,Metro,Adidas Hoodie,Clothes,Jackets,New Launch,...,92.4,88.0,Competitive,Medium,5.0,79.0,1,2022,Q1,Spring
4,Bx_Chennai_033,Brandx_India Connect Chennai,Brandx_India,Mall Store,Chennai,Metro,Playstation 5,Gadgets,Gaming Consoles,Declining,...,82.9,89.5,Competitive,Low,2.0,110.0,1,2022,Q1,Spring

In [ ]:
# Check Dataset Information

df.info()

In [19]:
# Create Profit Amount Column

df["Profit_Amount"] = (df["Revenue"] * df["Profit_Margin"] / 100)

df[["Revenue","Profit_Margin","Profit_Amount"]].sample(10)

        Revenue  Profit_Margin  Profit_Amount
3829    16576.0          26.01      4311.4176
3049  2545772.0          18.67    475295.6324
3801    43542.0          17.89      7789.6638
4341  2381449.0          29.66    706337.7734
4279  2015298.0          26.59    535867.7382
2085   383964.0          15.34     58900.0776
4517  1585800.0          16.66    264194.2800
2076   797368.0          28.04    223581.9872
3922   372400.0          23.74     88407.7600
2746     3186.0          29.63       944.0118

In [20]:
# Create Stock Difference Column

df["Stock_Difference"] = (df["Quantity_Available"] - df["Units_Sold"])

df[["Quantity_Available","Units_Sold","Stock_Difference"]].head()

   Quantity_Available  Units_Sold  Stock_Difference
0               125.0        24.0             101.0
1               135.0        35.0             100.0
2               215.0        31.0             184.0
3               163.0        22.0             141.0
4               167.0        39.0             128.0

In [31]:
# Create Inventory Status Column

df["Inventory_Status"] = np.where(df["Quantity_Available"] < 100, "Low Stock",np.where(df["Quantity_Available"] <= 200, "Medium Stock","High Stock"))

df[["Quantity_Available","Inventory_Status"]].sample(3)

      Quantity_Available Inventory_Status
270                117.0     Medium Stock
1131               247.0       High Stock
1407                64.0        Low Stock

In [ ]:
# Create Inventory Status Column

df["Inventory_Status"] = np.where(
    df["Quantity_Available"] < 100,
    "Low Stock",
    np.where(
        df["Quantity_Available"] <= 200,
        "Medium Stock",
        "High Stock"
    )
)

df[["Quantity_Available",
    "Inventory_Status"]].sample(5)

In [ ]:
# Create Revenue Per Unit Column

df["Revenue_Per_Unit"] = (
    df["Revenue"] /
    df["Units_Sold"]
)

df[["Revenue",
    "Units_Sold",
    "Revenue_Per_Unit"]].sample(5)

In [ ]:
# Verify Newly Created Columns

print(df[[
    "Profit_Amount",
    "Stock_Difference",
    "Inventory_Status",
    "Revenue_Per_Unit"
]].head())

In [34]:
print(x ======= x ======= x ======= x ======= x ======= x ======= x ======= x ======= x ======= x ======= x ======= x =======)

SyntaxError: invalid syntax (2471857596.py, line 1)

In [35]:
# Task 2: Transform Data

# Transform Revenue into Revenue Category

df["Revenue_Category"] = np.where(
    df["Revenue"] < 5000,
    "Low Revenue",
    np.where(
        df["Revenue"] < 10000,
        "Medium Revenue",
        "High Revenue"
    )
)

df[["Revenue", "Revenue_Category"]].head()

     Revenue Revenue_Category
0     7320.0   Medium Revenue
1     1645.0      Low Revenue
2    66340.0     High Revenue
3    77748.0     High Revenue
4  1976364.0     High Revenue

In [36]:
# Transform Customer Satisfaction Ratings

df["Customer_Feedback"] = np.where(
    df["Customer_Satisfaction"] >= 4,
    "Satisfied",
    "Needs Improvement"
)

df[[
    "Customer_Satisfaction",
    "Customer_Feedback"
]].head()

   Customer_Satisfaction  Customer_Feedback
0                    4.0          Satisfied
1                    3.9  Needs Improvement
2                    4.3          Satisfied
3                    4.4          Satisfied
4                    3.9  Needs Improvement

In [37]:
# Create Discount Category

df["Discount_Category"] = np.where(
    df["Max_Discount_Offered"] < 10,
    "Low Discount",
    np.where(
        df["Max_Discount_Offered"] < 20,
        "Medium Discount",
        "High Discount"
    )
)

df[["Max_Discount_Offered", "Discount_Category"]].sample(5)

      Max_Discount_Offered Discount_Category
4960                     9      Low Discount
4063                    12   Medium Discount
2239                    17   Medium Discount
3279                     6      Low Discount
4258                    38     High Discount

In [42]:
# Create Delivery Speed Category

df["Delivery_Speed"] = np.where(df["Delivery_Time"] <= 5,"Fast Delivery", "Standard Delivery")

df[["Delivery_Time","Delivery_Speed"]].sample(10)

      Delivery_Time     Delivery_Speed
2769            3.0      Fast Delivery
2353            5.0      Fast Delivery
1884            7.0  Standard Delivery
4603            1.0      Fast Delivery
2918            7.0  Standard Delivery
526             1.0      Fast Delivery
4669            2.0      Fast Delivery
3386            6.0  Standard Delivery
1280            4.0      Fast Delivery
2884            5.0      Fast Delivery

In [39]:
# Display Transformed Columns

print(df[[
    "Revenue_Category",
    "Customer_Feedback",
    "Discount_Category",
    "Delivery_Speed"
]].head())

  Revenue_Category  Customer_Feedback Discount_Category     Delivery_Speed
0   Medium Revenue          Satisfied      Low Discount  Standard Delivery
1      Low Revenue  Needs Improvement     High Discount      Fast Delivery
2     High Revenue          Satisfied     High Discount      Fast Delivery
3     High Revenue          Satisfied     High Discount      Fast Delivery
4     High Revenue  Needs Improvement     High Discount      Fast Delivery

In [40]:
# Check Dataset Information

df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 5146 entries, 0 to 5145
Data columns (total 55 columns):
 #   Column                 Non-Null Count  Dtype
---  ------                 --------------  -----
 0   Store_ID               5146 non-null   object
 1   Store_Name             5146 non-null   object
 2   Brand_Name             5146 non-null   object
 3   Store_Type             5146 non-null   object
 4   City                   5146 non-null   object
 5   City_Tier              5146 non-null   object
 6   Product_Name           5146 non-null   object
 7   Category               5146 non-null   object
 8   Sub_Category           5146 non-null   object
 9   Product_Stage          5146 non-null   object
 10  Quantity_Available     5146 non-null   float64
 11  Units_Sold             5146 non-null   float64
 12  Unit_Price             5146 non-null   int64
 13  Cost_Price             5146 non-null   int64
 14  Revenue                5146 non-null   float64
 15  Profit_Margin          5146 non-null   float64
 16  Average_Order_Value    5146 non-null   int64
 17  Inventory_Turnover     5146 non-null   float64
 18  Days_of_Stock          5146 non-null   int64
 19  Customer_Segment       5146 non-null   object
 20  Sales_Channel          5146 non-null   object
 21  Payment_Method         5146 non-null   object
 22  Supplier               5146 non-null   object
 23  Supplier_Rating        5146 non-null   object
 24  Promotion_Type         5146 non-null   object
 25  Promotion_Impact       5146 non-null   float64
 26  Max_Discount_Offered   5146 non-null   int64
 27  Return_Rate            5146 non-null   float64
 28  Return_Reason          5146 non-null   object
 29  Customer_Satisfaction  5146 non-null   float64
 30  Online_Rating          5146 non-null   float64
 31  Review_Count           5146 non-null   int64
 32  Sales_Rep_Experience   5146 non-null   int64
 33  Sales_Rep_Rating       5146 non-null   float64
 34  Market_Share           5146 non-null   float64
 35  Competition_Level      5146 non-null   object
 36  Competitor_Count       5146 non-null   int64
 37  Brand_Loyalty          5146 non-null   float64
 38  Brand_Awareness        5146 non-null   float64
 39  Price_Competitiveness  5146 non-null   object
 40  Weather_Impact         5146 non-null   object
 41  Delivery_Time          5146 non-null   float64
 42  Shipping_Cost          5146 non-null   float64
 43  Month                  5146 non-null   int64
 44  Year                   5146 non-null   int64
 45  Quarter                5146 non-null   object
 46  Season                 5146 non-null   object
 47  Profit_Amount          5146 non-null   float64
 48  Stock_Difference       5146 non-null   float64
 49  Inventory_Status       5146 non-null   object
 50  Revenue_Per_Unit       5146 non-null   float64
 51  Revenue_Category       5146 non-null   object
 52  Customer_Feedback      5146 non-null   object
 53  Discount_Category      5146 non-null   object
 54  Delivery_Speed         5146 non-null   object
dtypes: float64(18), int64(10), object(27)
memory usage: 2.2+ MB